### PR TITLE
Make use of swupd's --path option for repair

### PR DESCRIPTION
**Pull request by matthewrsj**
The 'Repair' option in Ister was failing to complete the repair due to a
failed network connection in the chroot. Instead of chrooting and trying
to set up a network, the path to the mounted host OS can be provided to
swupd via the --path option. This removes the complicated chroot
requirements and fixes the 'Repair' option.

Signed-off-by: Matthew Johnson <matthew.johnson@intel.com>

AKA: RTFM

### CODE REVIEW

**Comment by matthewrsj** [comment]
I seriously can't believe I missed this the first time.

**Comment by bryteise** [comment]
Just confirming, is /boot already mounted under the target as well?

**Comment by matthewrsj** [comment]
Well, not after this change, but that is how it used to be done for a repair.

**Comment by matthewrsj** [comment]
Sorry, yes, /boot is mounted. still..

**Comment by bryteise** [comment]
Oh good. thanks.

**Pull request merged**
