### PR TITLE
Enhance run command

### PR DESCRIPTION
**Pull request by dedekind**
This pull request includes the other 2 requests I sent earlier - "pylint cleanups" and "changing root user".
I will rebase this pull request f needed later.

This pull request adds these 3 commits:
Enhance run_command()
ister: split run_command()
ister_test: improve tracability

With these changes 'run_command()' is much nicer and now I can actually see 'swupd' progress "real-time":

Running command stdbuf -o 0 swupd verify --install --path=/mnt/sysimage --manifest=latest --contenturl=http://linux-ftp.jf.intel.com/pub/mirrors/clearlinux/update --versionurl=http://linux-ftp.jf.intel.com/pub/mirrors/clearlinux/update --statedir=/var/lib/swupd
Verifying version 25040
Downloading packs...
Extracting bootloader pack for version 24630
Extracting dev-utils pack for version 25040
Extracting git pack for version 25000
Extracting editors pack for version 24950
...

Without this patch we do no see that. Instead, we have a huge delay, and than bulk of output - millions of dots from stdout and then the "Extracting" messages from stderr of swupd.

Enjoy the enhancement. I do enjoy it, at least :)

### CODE REVIEW

**Comment by dedekind** [comment]
If you can, please, review/pull pull request in the order they arrive, I noticed you do it in reverse order.
Otherwise I do not know what happens if you decide to pull request #150 and then this one, because #150 includes this one.

I've addressed all your comments and re-testing now. Will re-submit. Thanks!

**Comment by bryteise** [comment]
Ugh yea, I didn't pay enough attention when doing the first merge and thought it included the other changes that I had reviewed. Sorry =(.

**Comment by bryteise** [comment]
Okay, this looks good. Is this PR okay to merge now?

**Comment by dedekind** [comment]
Yes, thanks.

**Pull request merged**
