### PR TITLE
Add ascii image of Clear Linux Penguin to SplashScreen

### PR DESCRIPTION
**Pull request by matthewrsj**
Remove introduction paragraph because this pushes much of the text off
the screen on widescreen monitors when the penguin is present.

Signed-off-by: Matthew Johnson <matthew.johnson@intel.com>

### qemu
penguin

### Bare metal
img_0039

### CODE REVIEW

**Comment by matthewrsj** [comment]
Another option:

penguin2

**Comment by matthewrsj** [comment]
Something with color: 
penguinoutline

**Comment by sofar** [comment]
that last one is promising, maybe clean it up a little bit more, though :)

**Comment by rnesius** [comment]
Looking better! :)

**Comment by matthewrsj** [comment]
This is on hold - will not be included in Ister 3.0

**Pull request closed without merging**
