### PR TITLE
Resize network configure options on message length

### PR DESCRIPTION
**Pull request by matthewrsj**
Dynamically set uwrid.Padding for network configuration buttons based
on the length of the message in the buttons. This creates buttons that
look like this:

```
< Button message >
```

rather than this:

```
< Button message                                                     >
```

Signed-off-by: Matthew Johnson <matthew.johnson@intel.com>

### CODE REVIEW

**Comment by bryteise** [comment]
Was this only an issue with the proxy page? It would seem like this would be something all buttons would want to use.

**Comment by matthewrsj** [comment]
So, there are other buttons, but they are on pages that are only for buttons. I thought keeping them the width of the page made sense. Another example is the nav bar, but I thought those buttons should all be the same size as well.

chooseact

**Comment by bryteise** [comment]
Personally I'd rather keep the button look consistent across the UI but we probably want additional feedback from others before making a decision on that.

**Comment by matthewrsj** [comment]
Looking through the screens, I'm agreeing with you that the buttons would look fine if they were consistently the length of the message. I'm working on this now.

**Comment by matthewrsj** [comment]
@bryteise done. All buttons are now created to look consistent and use the same wrapper method to do so.

**Comment by bryteise** [comment]
Merged in 2143879.

**Pull request closed without merging**
