### PR TITLE
RFE: Add sudo users to the sudo group, not to the sudoers config file

### PR DESCRIPTION
**Pull request by ikeydoherty**
Full explanation in the commit itself. It may be that you intend for this behaviour, but in case
it isn't, here's an alternative. ^^

### CODE REVIEW

**Comment by ikeydoherty** [comment]
^ lol @ looking for rake

**Comment by bryteise** [comment]
Yea, I need to take the time to setup travis here, I welcome pull requests for that =P.

**Comment by bryteise** [comment]
Nice use of the chroot wrapper btw.

**Comment by ikeydoherty** [comment]
Well tbh it took me a while to figure out how to make the test happy. At which point I became most impressed, that's a nice test system you have :D

**Comment by bryteise** [comment]
When you think about the amount of pain mocking gives you lol. Thank goodness for python at least it is much simpler.

**Comment by ikeydoherty** [comment]
Yeah, something like this in C would be a god send ..

**Pull request merged**
